---
- name: create file 
  hosts: kube_node
  file: 
       path: /root/my.conf
       state: touch
       owner: root
       group: root
       mode: 0600

- name: copy file between locations on the remote host
  copy:
    src: /root/my.conf
    remote_src: true
    dest: /tmp/test_file2
